postgres:
  image: postgres
rails:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/mnt/somerville-teacher-tool
  ports:
    - "3000:3000"
  links:
    - postgres
webpack:
  build: ui/.
  command: npm run develop
  ports:
    - "8666:8666"
  volumes:
    - ./ui:/mnt/ui